### ISSUE TITLE
Crashing on React 19?

### ISSUE THREAD

**Issue by ninoM** [rosskhanas/react-qr-code#256]
Component itself is crashing with no logs to console. Only error message I could get was this `bad rs block @ typeNumber:1/errorCorrectLevel:undefined`

**Comment by quangIle** [comment]
Hi, I have just encountered this problem. This is because React 19 remove defaultProps [here](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops). Therefore, in this [line](https://github.com/rosskhanas/react-qr-code/blob/d286eb7b9663ba816a46a7844e7470fc2dc93e7a/src/index.js#L25) `level` got `undefinded`. 

You now need to add `level` props yourself to fix this:
```jsx
<QRCode
   level="L"
   value="abc" 
/>
```

**Comment by rosskhanas** [comment]
https://github.com/rosskhanas/react-qr-code/commit/66cff5735f916c20e6638a9b1c5cf4e34db20f63

No default props anymore.
